import os


MONNIFY_API_KEY = os.environ.get("MONNIFY_API_KEY", "")
MONNIFY_SECRET_KEY = os.environ.get("MONNIFY_SECRET_KEY", "")
MONNIFY_CONTRACT_CODE = os.environ.get("MONNIFY_CONTRACT_CODE", "")
MONNIFY_CURRENCY_CODE = os.environ.get("MONNIFY_CURRENCY_CODE", "")
MONNIFY_BASEURL_PREFIX = os.environ.get("MONNIFY_BASEURL_PREFIX", "")
