# Generated by Django 5.1.3 on 2024-11-17 16:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("merchant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Address Name"
                    ),
                ),
                ("address_1", models.CharField(max_length=40, verbose_name="Address")),
                (
                    "address_2",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="Address 2 (Optional)",
                    ),
                ),
                (
                    "locality",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="City"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("Lagos", "Lagos")],
                        default="Lagos",
                        max_length=40,
                        verbose_name="State",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[("Nigeria", "NIGERIA")],
                        default="Nigeria",
                        max_length=40,
                        verbose_name="Country/Region",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        choices=[("NIG", "NIG")],
                        default="NIG",
                        max_length=40,
                        verbose_name="CountryCode/RegionCode",
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="zip Code"
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="merchant.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "address",
                "verbose_name_plural": "addresses",
            },
        ),
    ]
