version: "3.9"
   
services:
  db:
    container_name: db
    image: postgres:15-alpine
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: "always"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: app
    build: .
    command: ./conf/scripts/local/provide_env.sh
    env_file:
      - ./conf/env_variables/.env
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: "service_healthy"
    restart: "always"

# volumes:
#   postgres_data: