# Generated by Django 5.1.3 on 2024-11-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrtag",
            name="qr_image",
            field=models.FileField(editable=False, null=True, upload_to="qrcodes"),
        ),
    ]
