# Generated by Django 5.1.3 on 2024-11-17 15:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankDetail",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("bank", "BANK"), ("virtual", "VIRTUAL")],
                        default="bank",
                        max_length=50,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("bank", "BANK"),
                            ("paystack", "PAYSTACK"),
                            ("monnify", "MONNIFY"),
                        ],
                        default="bank",
                        max_length=50,
                    ),
                ),
                ("account_name", models.CharField(max_length=250)),
                ("account_number", models.CharField(max_length=20, unique=True)),
                ("bank_name", models.CharField(max_length=100)),
                ("bank_code", models.CharField(max_length=100)),
                ("bvn", models.CharField(blank=True, max_length=20, null=True)),
                ("card_number", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "recipient_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "account_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reservation_reference",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("default", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
