# Generated by Django 5.1.3 on 2024-12-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0002_runningcost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runningcost",
            name="currency",
            field=models.CharField(
                choices=[("NGN", "NGN"), ("USD", "USD"), ("EUR", "EUR")],
                default="NGN",
                max_length=50,
            ),
        ),
    ]
