# Generated by Django 5.1.3 on 2024-12-30 10:06

import applications.administrator.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0003_alter_runningcost_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="runningcost",
            name="circular_thumbnail",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=applications.administrator.media.administrator_cir_thumbnail,
            ),
        ),
        migrations.AddField(
            model_name="runningcost",
            name="thumbnail",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=applications.administrator.media.administrator_thumbnail,
            ),
        ),
    ]
