# Generated by Django 5.1.3 on 2025-01-05 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0004_runningcost_circular_thumbnail_runningcost_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="runningcost",
            name="circular_thumbnail",
        ),
        migrations.RemoveField(
            model_name="runningcost",
            name="thumbnail",
        ),
    ]
